name = "stewardiq-convex"
compatibility_date = "2025-06-24"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[routes]]
pattern = "stewardiqconvex.alexander-klusa.me"
custom_domain = true
